### ISSUE TITLE
Request for copywriting 

### ISSUE THREAD

**Issue by princekelly1** [superoo7/statBot#1]
Hi, 
I see alot of work on this not, but sadly am not a developer but a copy writer, I would love to write and submit pull request for "About Us" For this project.

**Comment by superoo7** [comment]
Sure, go ahead, once I had done the project I will also start documenting. Thanks for helping out

**Comment by princekelly1** [comment]
Thanks
, and am happy to be of help. I would submit pull request, you can request
for correcting and merge.
