### ISSUE TITLE
better logo and name suggestion

### ISSUE THREAD

**Issue by superoo7** [superoo7/statBot#7]
I will leave this open until fixed.

I am looking for a better logo for the project and name suggestion to replace `statBot`

**Comment by olu4mide** [comment]
I will like to design the logo for the bot. Do you have any concept in mind or color scheme?

**Comment by superoo7** [comment]
Thanks for the offering @solomon507 

This was the current icon for the bot
![icon-384x384](https://user-images.githubusercontent.com/15358452/48182738-4dba6d00-e367-11e8-8396-d666c26bf1cc.png)

we might rename the bot name in near future, so it is better to use a robot icon or anything else instead of `statbot` as the name.

Just make sure that the icon is in round shape.

**Comment by olu4mide** [comment]
Okay. I will try and come up with something

**Comment by olu4mide** [comment]
Would you like me to incorporate Steem logo? If yes, the new one or the old one?

**Comment by olu4mide** [comment]
Can I reach you via discord? I am Solomon507#9787 on discord.

**Comment by superoo7** [comment]
You can join our discord at https://discord.gg/J99vTUS

**Comment by olu4mide** [comment]
Here is the logo. This is the ong format, I will provide a link that contains the svg, source file and other files. 

![logo](https://user-images.githubusercontent.com/36331413/48287985-f271a300-e46a-11e8-8297-c976dad882b4.png)

![statbot](https://user-images.githubusercontent.com/36331413/48286426-dfa89f80-e465-11e8-9ac6-c0491ba7c1eb.png)

![statbot1](https://user-images.githubusercontent.com/36331413/48284577-167bb700-e460-11e8-8075-233d5ddca6ec.png)
![statbotv](https://user-images.githubusercontent.com/36331413/48284582-18457a80-e460-11e8-8a10-4994f0203d10.png)
![statbotv1](https://user-images.githubusercontent.com/36331413/48286434-e8997100-e465-11e8-86e8-f6e5e27c05fa.png)

Here are color varations
![color variations 2](https://user-images.githubusercontent.com/36331413/48284676-5d69ac80-e460-11e8-934b-49577193ed14.png)
![color variations](https://user-images.githubusercontent.com/36331413/48286463-01a22200-e466-11e8-9bff-6d4041b0a17e.png)


The idea
![idea](https://user-images.githubusercontent.com/36331413/48284704-71ada980-e460-11e8-85bc-ac0ceba16797.png)

**Comment by superoo7** [comment]
Looks good! appreciate it 😄!

**Comment by olu4mide** [comment]
https://drive.google.com/open?id=1flB_qY7VhNfq0aAEL-jgymKT9HdQFuWb

Here is a link to the file.

I will make a pull request

**Comment by superoo7** [comment]
I guess we will stick back to statBot, unless there's someone come up with a better name. Closing this issue for now. (In case anyone got a better name, just reopen this issue)
